name: "Build and release"

on:
  push:
    branches: [master]

jobs:
  build_test:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        nodejs: [12, 14, 16, 18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      
      - run: scripts/setup-firebase-emulator-for-tests.sh
      
      - run: npm ci
      
      - run: npm run build
      
      - run: npm run testall-with-coverage-lcov
      
      - run: npm run upload-coverage
      
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build_test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
            
      - run: npm ci
      - run: npm run build      
      - run: npx semantic-release