name: "Build and release"

on:
  push:
    branches: [master, _jl_introduce_github_actions]

jobs:
  build_test_release:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      strategy:
      matrix:
        nodejs: [10, 12, 14, 16, 18]
        release: [false]
        include:
          - release: true
            nodejs: 16

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      
      - run: scripts/setup-firebase-emulator-for-tests.sh
      
      - run: npm ci
      
      - run: npm run build
      
      - run: npm run testall-with-coverage-lcov
      
      - run: npm run upload-coverage
      
      - if: ${{ matrix.release }} == true
        run: echo "Would deploy"